### PR TITLE
[jsk_interactive_marker] Remove dependency on jsk_pcl_ros for separated build

### PR DESCRIPTION
**Pull request by wkentaro**
Depends on https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827

### CODE REVIEW

**Comment by k-okada** [comment]
this requires to change client code if someone use this message, please confirm potential users.

**Comment by wkentaro** [comment]
```
% rossrv md5 jsk_recognition_msgs/CallSnapIt
00529f1ccb0137f3a14b6d5b281f9a3c
```

```
% rossrv md5 jsk_pcl_ros/CallSnapIt
00529f1ccb0137f3a14b6d5b281f9a3c
```

The messages are completely the same, so I think there is no problem.
Tested as below:
https://gist.github.com/wkentaro/6ce45ce92ac615bd07d6072ed67c22e7

**Comment by wkentaro** [comment]
Could you please merge this?

**Comment by k-okada** [comment]
sorry for late, did you run travis test after we merged https://github.com/jsk-ros-pkg/jsk_recognition/pull/1983?

**Comment by wkentaro** [comment]
No. Should I add test with installing from source?

**Comment by k-okada** [comment]
no you do not have to add new test, but let's restart travis job after new
release -> https://github.com/ros/rosdistro/pull/13393

--
◉ Kei Okada


2016-12-11 19:06 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
That sounds good.

**Comment by k-okada** [comment]
@wkentaro 
```
13:14:14 [jsk_perception] -- Using these message generators: gencpp;geneus;genlisp;genpy 
13:14:16 [jsk_perception] CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 
13:14:16 [jsk_perception]   Could not find a configuration file for package opencv_apps. 
13:14:16 [jsk_perception]  
13:14:16 [jsk_perception]   Set opencv_apps_DIR to the directory containing a CMake configuration file 
13:14:16 [jsk_perception]   for opencv_apps.  The file will have one of the following names: 
13:14:16 [jsk_perception]  
13:14:16 [jsk_perception]     opencv_appsConfig.cmake 
13:14:16 [jsk_perception]     opencv_apps-config.cmake 
13:14:16 [jsk_perception]  
13:14:16 [jsk_perception] Call Stack (most recent call first): 
13:14:16 [jsk_perception]   CMakeLists.txt:17 (find_package) 
13:14:16 [jsk_perception]  
13:14:16 [jsk_perception]  
13:14:16 [jsk_perception] -- [roseus.cmake] loading roseus.cmake from jsk_perception 
13:14:16 [jsk_perception] -- [roseus.cmake] roseus 1.3.9 
```

**Comment by wkentaro** [comment]
hydo?

**Comment by wkentaro** [comment]
... why?

**Comment by wkentaro** [comment]
Maybe because jsk_recognition is installed without version specification.
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/.travis.rosinstall.hydro#L1-L3

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1726

**Comment by wkentaro** [comment]
I think https://github.com/jsk-ros-pkg/jsk_recognition/pull/1984 adds dependency on opencv_apps and released with 1.0.0 of jsk_recognition.
So jsk_visualization should depend on the 0.3.9, I think.

**Comment by wkentaro** [comment]
```
[jsk_interactive_marker] /workspace/ros/ws_jsk_visualization/src/jsk_visualization/jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp:45:45: fatal error: jsk_recognition_msgs/CallSnapIt.h: No such file or directory 
```

**Pull request merged**
