### PR TITLE
Run push build only on the master branch

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
does this run ci for forked PR?

**Comment by wkentaro** [comment]
Yes. As I demonstrate in https://github.com/jsk-ros-pkg/jsk_common/pull/1551.

**Comment by k-okada** [comment]
ok, let's see, please create new PR . how about fix the problem of clicking images on the top page. it goes to https://github.com/jsk-ros-pkg/jsk_visualization/blob/master

**Comment by wkentaro** [comment]
It works: https://github.com/jsk-ros-pkg/jsk_visualization/pull/681

**Pull request merged**
