### PR TITLE
update perspective for noetic

### PR DESCRIPTION
**Pull request by knorth55**
now perspective does not work in `resource/` for noetic.
I fix the perspective

### CODE REVIEW

**Comment by k-okada** [comment]
thank you
1) did you test if this works on melodic ?
2) did you fix this manually? From my experience, the problem was QByteArray and could be fixed by 
```
sed -i s@QByteArray\(\'@QByteArray\(b\'@ *.perspective
```
If this is true, may be we need to fix `rqt_image_view2_button.perspective` too

**Comment by knorth55** [comment]
i haven't tested on melodic.
I overwrite the file from noetic.

> If this is true, may be we need to fix rqt_image_view2_button.perspective too

I thought the same thing, but i can open the `image_view2` perspective.

**Comment by knorth55** [comment]
@k-okada 

>If this is true, may be we need to fix rqt_image_view2_button.perspective too

I checked wrongly. you are right.
we need to change the array to `binarray` array, too.

**Comment by knorth55** [comment]
I haven't tested on python2, but i think it works.
`python2` treat `b''` as string, as far as I know.

```
$ python2
Python 2.7.18 (default, Jul  1 2022, 12:27:04)
[GCC 9.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = b'hoge'
>>> a
'hoge'
>>> type(a)
<type 'str'>
```

**Pull request merged**
