### PR TITLE
Add jade travis test

### PR DESCRIPTION
**Pull request by wkentaro**
Please wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/102 to be merged
and submodules to be updated.

### CODE REVIEW

**Comment by wkentaro** [comment]
fail with unexpected error:
```
+++sudo apt-get install -y -q -qq python-rosdep python-wstool python-catkin-tools ros-jade-rosbash
E: Unable to locate package ros-jade-rosbash
++++error
```

it seems that rosbash is released for jade.
http://www.ros.org/debbuild/jade.html?q=rosbash

**Comment by k-okada** [comment]
Wait a moment, package.ros.org may under sync 

--
◉ Kei Okada

2015/08/27 20:03、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
```
[jsk_interactive_marker]   Could not find a package configuration file provided by "jsk_pcl_ros" with 
[jsk_interactive_marker]   any of the following names:                          
[jsk_interactive_marker]                                                        
[jsk_interactive_marker]     jsk_pcl_rosConfig.cmake                            
[jsk_interactive_marker]     jsk_pcl_ros-config.cmake                           
[jsk_interactive_marker]                                  
```

**Comment by k-okada** [comment]
Please rebase origin/master

**Comment by wkentaro** [comment]
PLZ merge this

**Pull request merged**
