### PR TITLE
use QFileDialog for file select

### PR DESCRIPTION
**Pull request by knorth55**
SOMOSOMO, why do we put file path by string???????????????????
i feel like im in 1970s. (mouse is from 1983)
https://en.wikipedia.org/wiki/Apple_Lisa

this PR change to use QFileDialog to open yaml file.
I only tested on noetic

https://user-images.githubusercontent.com/9300063/234813532-4c18cc03-032a-4950-a449-6ca39016061e.mp4

### CODE REVIEW

**Comment by k-okada** [comment]
please test on melodic @knorth55

**Comment by tkmtnt7000** [comment]
I tested on melodic, but clicking and calling `dummy/button` service seemed to fail.
is it expected behavior?

https://user-images.githubusercontent.com/67531577/235175823-1f345e15-3b7b-4cc9-9c30-072f28b1ec1d.mp4

**Comment by knorth55** [comment]
yes you need service server.
you can launch the nodes in `sample/sample_service_button.launch`, but gui also launches, too.
 please ignore the gui or disable it, and run `rqt_gui`.

`rqt_gui` saves default config automatically, so please remove `~/.config/ros.org/rqt_gui.ini` to refresh it.

**Comment by tkmtnt7000** [comment]
Thank you.
I have confirmed that this PR works on melodic, too.

https://user-images.githubusercontent.com/67531577/235291864-6aa248d5-2bf4-4153-bcb3-ff3f1121143e.mp4

**Comment by knorth55** [comment]
Super!

**Comment by tokoro10g** [comment]
This PR looks really nice! Would you mind merging this since there seem no issues?

**Pull request merged**
