### PR TITLE
[jsk_rqt_plugins] fix hist.py to work on kinetic

### PR DESCRIPTION
**Pull request by knorth55**
this PR is improved PR of #688.
it works with `matplotlib` `1.5.1`

### CODE REVIEW

**Comment by knorth55** [comment]
@iory can you check again with this PR?
I think the problem about matplotlib is solved.

**Comment by iory** [comment]
I also checked this PR and it works too!

image

**Comment by knorth55** [comment]
For python syntax check, I use `flake8` + `hacking` ref: https://qiita.com/kitsuyui/items/5ab4608003a29ff7689f.
it uses openstack hacking guideline. https://docs.openstack.org/hacking/latest/
However, for normal users, `roslint_python` is enough for them.

**Comment by k-okada** [comment]
Please add them to the Travis CI, if you want to keep changing coding style for every PR,

**Pull request merged**
