### PR TITLE
Support kinetic on jsk_rviz_plugins and jsk_rqt_plugins

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/jsk-ros-pkg/jsk_visualization/issues/648

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this?

**Comment by k-okada** [comment]
jsk_recognition is almost ready for kinect, so let wait for https://github.com/ros/rosdistro/pull/13397 and https://github.com/pr2-gbp/robot_self_filter-gbp/issues/1

**Comment by wkentaro** [comment]
Oh, I see. Thank you for your devotion.

**Comment by k-okada** [comment]
Travis kinetic check has been done at #654

**Pull request closed without merging**
