### PR TITLE
Deploy documents on readthedocs

### LINKED ISSUE #485: Documentation like jsk_recognition
I'd like to add documentation to jsk_visualization like jsk_recognition.

@wkentaro Could you prepare readthedocs?

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #485

### CODE REVIEW

**Comment by wkentaro** [comment]
@garaemon 

I'm done, but actually I'm not sure how to split the README of jsk_rviz_plugins.
https://github.com/jsk-ros-pkg/jsk_visualization/tree/master/jsk_rviz_plugins#jsk_rviz_plugins
(some parts are not one header with one section for one plugin)

**Comment by wkentaro** [comment]
So, could you split the README of jsk_rviz_plugins? @garaemon 
It seems that you're the main author of that document and easy for you to organize them.

not perfect but I used this script to split jsk_pcl_ros, jsk_perception README.
https://gist.github.com/wkentaro/e2e3fb4ca07639926fdb

**Comment by garaemon** [comment]
> So, could you split the README of jsk_rviz_plugins? @garaemon 
> It seems that you're the main author of that document and easy for you to organize them.

Yeah, I will split it after merge it.

**Comment by wkentaro** [comment]
Ok, please merge after the test.

2015年10月1日木曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> So, could you split the README of jsk_rviz_plugins? @garaemon
> <https://github.com/garaemon>
> It seems that you're the main author of that document and easy for you to
> organize them.
>
> Yeah, I will split it after merge it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/pull/487#issuecomment-144621587>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
```
+eval '(cd doc && source setup.sh && make html)'
++cd doc
/home/travis/build.sh: line 41: cd: doc: No such file or directory
```

**Comment by garaemon** [comment]
sudo required? or --user?

```
  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/req/req_install.py", line 740, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/req/req_install.py", line 949, in move_wheel_files
      isolated=self.isolated,
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg/pip/wheel.py", line 205, in clobber
      os.makedirs(destdir)
    File "/usr/lib/python2.7/os.py", line 157, in makedirs
      mkdir(name, mode)
  OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/certifi-2015.9.6.2.dist-info'
```

**Comment by wkentaro** [comment]
that's because here was no virtualenv command.
I install it before the testing line.

**Pull request merged**
