### PR TITLE
Migrate srv files from jsk_pcl_ros to jsk_recognition_msgs

### PR DESCRIPTION
**Pull request by wkentaro**
see
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1914

### CODE REVIEW

**Comment by k-okada** [comment]
need to wait for jade release? -> https://github.com/ros/rosdistro/pull/13266、please restart travis after new deb is releasead @wkentaro

**Comment by k-okada** [comment]
## Background

Some packages in jsk_visualization depends on jsk_pcl_ros because it uses the srv files.
But jsk_pcl_ros is a very large package and the dependency should be avoided ideally.
The solution is placing msg/srv files into jsk_recognition_msgs.

## Plans

Merge this after jsk_recognition_msgs is released: http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_recognition_msgs

- Release this pacakge.
- Remove jsk_pcl_ros/srv.
- Release jsk_pcl_ros.

## Related PRs

jsk-ros-pkg/jsk_recognition#1827
jsk-ros-pkg/jsk_recognition#1914

**Comment by k-okada** [comment]
@wkentaro should we add version_gte >= 1.0.0 for jsk_recognition_msg?

**Comment by wkentaro** [comment]
@k-okada You're right. Thanks. -> #651

**Pull request merged**
