### PR TITLE
[jsk_rqt_plugins] Describe about rqt_yn_btn

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
we can put this into upstream package

**Comment by wkentaro** [comment]
Sent PR: https://github.com/ros-visualization/rqt_common_plugins/pull/342

**Comment by wkentaro** [comment]
@k-okada

I was said that I should release this plugin as another package and hosted GitHub as another repository. 
But in jsk_visualization, all rqt plugins are in a package jsk_rqt_plugins. (that seems not a common practice)
So I'm creating a package on root of jsk_visualization. Do u agree?

**Comment by k-okada** [comment]
creating single package is super bad idea unless you can maintain them next
5 years.
btw, can we use rqt_srv package for sending yes/no service?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
> creating single package is super bad idea unless you can maintain them next
5 years.

why? I think you misunderstanding my idea.
please read again. >>>

> But in jsk_visualization, all rqt plugins are in a package jsk_rqt_plugins. (that seems not a common practice)
So I'm creating a package on root of jsk_visualization. Do u agree?

**Comment by wkentaro** [comment]
> btw, can we use rqt_srv package for sending yes/no service?

No it is only for browsing srv files.

**Pull request merged**
