### PR TITLE
[jsk_rviz_plugins] add segment_array_display

### PR DESCRIPTION
**Pull request by mmurooka**
Updated PR of https://github.com/jsk-ros-pkg/jsk_visualization/pull/665.

### CODE REVIEW

**Comment by k-okada** [comment]
I have discussed dependency of jsk_ packages, and we need to avoid circular dependency as much as possible.
At this moment does jsk_recognition depends on jsk_visualization? or jsk_visualization depends on jsk_recognition? 
Cc: @wkentaro  
```
Still running (5 of 60): catkin build --summarize --no-status -p4 --make-args -j8 --
The command catkin build --summarize --no-status -p4 --make-args -j8 -- exited with 1.
Log:
NOTICE: Could not determine the width of the terminal. A default width of 80 will be used. This warning will only be printed once.
_______________________________________________________________________________
Errors << jsk_rviz_plugins:make /home/travis/ros/ws_jsk_visualization/logs/jsk_rviz_plugins/build.make.000.log
/home/travis/ros/ws_jsk_visualization/src/jsk_visualization/jsk_rviz_plugins/src/close_all_tool.h:0: Note: No relevant classes found. No output generated.
/home/travis/ros/ws_jsk_visualization/src/jsk_visualization/jsk_rviz_plugins/src/open_all_tool.h:0: Note: No relevant classes found. No output generated.
/home/travis/ros/ws_jsk_visualization/src/jsk_visualization/jsk_rviz_plugins/src/overlay_picker_tool.h:0: Note: No relevant classes found. No output generated.
/home/travis/ros/ws_jsk_visualization/src/jsk_visualization/jsk_rviz_plugins/src/quiet_interactive_marker_display.h:0: Note: No relevant classes found. No output generated.
In file included from /home/travis/ros/ws_jsk_visualization/src/jsk_visualization/jsk_rviz_plugins/src/segment_array_display.cpp:35:0:
/home/travis/ros/ws_jsk_visualization/src/jsk_visualization/jsk_rviz_plugins/src/segment_array_display.h:40:47: fatal error: jsk_recognition_msgs/SegmentArray.h: No such file or directory
 #include <jsk_recognition_msgs/SegmentArray.h>
                                               ^
compilation terminated.
make[2]: *** [CMakeFiles/jsk_rviz_plugins.dir/src/segment_array_display.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/jsk_rviz_plugins.dir/all] Error 2
make: *** [all] Error 2
cd /home/travis/ros/ws_jsk_visualization/build/jsk_rviz_plugins; catkin build --get-env jsk_rviz_plugins | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

**Comment by wkentaro** [comment]
jsk_rviz_plugins depends on jsk_recognition_msgs and jsk_recognition_utils at build time.
jsk_pcl_ros depends on jsk_rviz_plugins at run time.

**Comment by k-okada** [comment]
ok, so this PR depends on jsjk_recognition_msgs is ok,  wait for
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2047

--
◉ Kei Okada


2017-04-07 16:29 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by mmurooka** [comment]
Yes, I've should write that, Sorry.

**Comment by mmurooka** [comment]
Updated according to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2047#issuecomment-296535050 update.
need to wait https://github.com/jsk-ros-pkg/jsk_recognition/pull/2047

**Comment by mmurooka** [comment]
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/.travis.yml#L25-L26
のUSE_DEB=true はjsk_recognition_msgsもdebで入るということであっていますでしょうか．

そうすると https://github.com/jsk-ros-pkg/jsk_recognition/pull/2047 がマージされましたが，
このPRのtravisは次のjsk_recognition_msgsのリリース後に通るようになると思います．

**Comment by iory** [comment]
I checked this PR on indigo and kinetic, and it works!

```
roslaunch jsk_rviz_plugins segment_array_sample.launch
```

The result of sample is here.

output

**Pull request merged**
