### PR TITLE
Remove has_key for python3 compatibility

### PR DESCRIPTION
**Pull request by adivardi**
This PR replaces the deprecated has_key function using the in keyword. has_key was deprectaed in python 3.x, so the current code fails when executed with a python3 interpreter.
Also changes pyyaml load to safe_load as it is a much safer option (this also gets rid of the warning in python3).
This fix should work on both python2 and 3.

After this PR, I was able to run button_general in python3.

Edit: Opening a new PR instead of #810 as I had to add some extra things to my other branch which I am not sure if to include in this PR.

### CODE REVIEW

**Comment by k-okada** [comment]
@adivardi thank you for contribution. merged in #817

**Comment by adivardi** [comment]
@k-okada Thanks.
You should also keep my fix for `yaml.safe_load()` instead of `yaml.load()`, as the load version is deprecated and unsafe. Currently it shows this warning:
```jsk_rqt_plugins/button_general.py:133: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.```

**Comment by k-okada** [comment]
Do you know when `yaml.load()` is deprecated? I'd like to keep
backward compatibility as much as possible. We still targeting at least
16.04.
--
◉ Kei Okada



2021年7月12日(月) 11:20 Adi Vardi ***@***.***>:

**Comment by adivardi** [comment]
It's was deprecated in pyyaml 5.1, but only with a warning (so the code still works now, even for me with Ubuntu Focal and ROS Noetic).
But `safe_load` was there since at least version 3.1 (which is the 1st release as far as I can tell), so it should work fine on 16.04 as well.

**Comment by k-okada** [comment]
@adivardi I see, add PR on  #818

**Comment by adivardi** [comment]
thanks! will you do a another release soon?

**Pull request closed without merging**
