### PR TITLE
Cleanup jsk_rviz_plugins package.xml

### PR DESCRIPTION
**Pull request by wkentaro**
- Remove dups
- Sort

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
this may requires another bloom-release hack...

**Comment by wkentaro** [comment]
I think there are no python packages. is it not enough?

2016年6月3日金曜日、Kei Okada<notifications@github.com>さんは書きました:

> Merged #604 <https://github.com/jsk-ros-pkg/jsk_visualization/pull/604>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/pull/604#event-680659718>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk7K5MQqUFCIFZcuLVziRRfIvhpkqks5qH53kgaJpZM4IsUh9>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
Sorry, It seems ok for this packge , but sometimes we have to
remove packages which is not released yet, or deprecated during bloom
process ,

--
◉ Kei Okada


On Fri, Jun 3, 2016 at 12:23 PM, Kentaro Wada <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I think there are no python packages. is it not enough?
>
> 2016年6月3日金曜日、Kei Okada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
> > Merged #604 <https://github.com/jsk-ros-pkg/jsk_visualization/pull/604>.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_visualization/pull/604#event-680659718
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AEHFk7K5MQqUFCIFZcuLVziRRfIvhpkqks5qH53kgaJpZM4IsUh9
> >
> > .
> >
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/pull/604#issuecomment-223481865>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3JsVCsdAOs9PDhSea6qjbg_KSqduks5qH542gaJpZM4IsUh9>
> .
>



-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Ok, I will consider about it.

2016年6月3日金曜日、Kei Okada<notifications@github.com>さんは書きました:

> Sorry, It seems ok for this packge , but sometimes we have to
> remove packages which is not released yet, or deprecated during bloom
> process ,
>
> --
> ◉ Kei Okada
>
>
> On Fri, Jun 3, 2016 at 12:23 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
>
> > I think there are no python packages. is it not enough?
> >
> > 2016年6月3日金曜日、Kei Okada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>さんは書きました:
> >
> > > Merged #604 <https://github.com/jsk-ros-pkg/jsk_visualization/pull/604
> >.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/jsk-ros-pkg/jsk_visualization/pull/604#event-680659718
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AEHFk7K5MQqUFCIFZcuLVziRRfIvhpkqks5qH53kgaJpZM4IsUh9
> > >
> > > .
> > >
> >
> >
> > --
> > 和田 健太郎 / Kentaro Wada
> > http://wkentaro.com
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_visualization/pull/604#issuecomment-223481865
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAeG3JsVCsdAOs9PDhSea6qjbg_KSqduks5qH542gaJpZM4IsUh9
> >
> > .
> >
>
>
>
> --
> --
> ◉ Kei Okada
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/pull/604#issuecomment-223541714>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk7uMAmHHRv4-LdLDihazPEKbDywCks5qH_0SgaJpZM4IsUh9>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Pull request merged**
