### PR TITLE
replace boost::shared_ptr by std::shared_ptr

### PR DESCRIPTION
**Pull request by christian-rauch**
This PR replaces `boost::shared_ptr` by `std::shared_ptr` and related methods, to build on ROS melodic.

These changes will break the kinetic build. Can you create a `melodic-devel` branch where I can rebase this on?
Also, the melodic CI job is missing `jsk_recognition_utils`.

### CODE REVIEW

**Comment by pazeshun** [comment]
Instead of requesting `melodic-devel`, you may be able to use `typedef` not to break kinetic build like:
https://github.com/start-jsk/jsk_apc/commit/4020d637d8aaf768118a9c338639c2f3ca47d8ef

I prefer this solution because having multiple branches will make many troubles such as backport missing.

**Comment by christian-rauch** [comment]
@pazeshun I used the urdf typedefs when possible and manually defined them for ROS indigo.

**Comment by knorth55** [comment]
I tested on my PC with indigo, and build succeeded.

**Comment by knorth55** [comment]
I tried sample launch and it works on indigo.
```bash
roslaunch jsk_interactive_marker sample_transformable_markers_client.launch
```

**Comment by k-okada** [comment]
@christian-rauch thank you very much for your efforts!!!!

**Pull request merged**
