### PR TITLE
[jsk_rviz_plugins] add marker publisher for classification result

### PR DESCRIPTION
**Pull request by furushchev**
multi_class

### CODE REVIEW

**Comment by k-okada** [comment]
nice, btw, how did you visualize histogram bar graph?

**Comment by furushchev** [comment]
@k-okada It is not related to this pull request. Sorry for confusion.
You can see this with `color_histogram_visualizer.py` at `jsk_recognition`
 https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/scripts/color_histogram_visualizer.py
like:
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/sample/sample_color_histogram.launch

**Comment by furushchev** [comment]
I want to check this node a bit more, please wait to merge, thanks!

**Comment by k-okada** [comment]
Sorry already merged, create anothe PR

**Comment by furushchev** [comment]
OK! That's no problem!

**Pull request merged**
