### PR TITLE
update .travis to 0.5.21

### PR DESCRIPTION
**Pull request by knorth55**
update jsk_travis to 0.5.21

### CODE REVIEW

**Comment by knorth55** [comment]
test fails because of https://github.com/jsk-ros-pkg/jsk_travis/issues/423

**Comment by knorth55** [comment]
I update this PR to 0.5.21

**Comment by knorth55** [comment]
@k-okada this PR passed travis test!

**Comment by knorth55** [comment]
@k-okada can you merge this PR for passing the test? #808 is waiting for merging.

**Comment by k-okada** [comment]
Thank you.

test on Action except noetic-full-test passed https://github.com/knorth55/jsk_visualization/actions
Travis test is also passed in https://travis-ci.com/github/jsk-ros-pkg/jsk_visualization/builds/226001885

**Review by k-okada — APPROVED** [review]

**Pull request merged**
