### PR TITLE
Fix problem of genjava error caused by not listed message_generation

### LINKED ISSUE #551: [jsk_interactive_marker] build fail  on generating java message

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #551

Modified:
  - jsk_interactive_markers/jsk_interactive_marker/package.xml

### CODE REVIEW

**Comment by k-okada** [comment]
I'm not sure why this fixes, but do we need find_package(catkin COMPONENT
message_generaion)????

2015年12月24日木曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Closes #551 <https://github.com/jsk-ros-pkg/jsk_visualization/issues/551>
>
> Modified:
>
>    - jsk_interactive_markers/jsk_interactive_marker/package.xml
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jsk-ros-pkg/jsk_visualization/pull/557
> Commit Summary
>
>    - Fix problem of genjava error caused by not listed message_generation
>
> File Changes
>
>    - *M* jsk_interactive_markers/jsk_interactive_marker/package.xml
>    <https://github.com/jsk-ros-pkg/jsk_visualization/pull/557/files#diff-0>
>    (1)
>
> Patch Links:
>
>    - https://github.com/jsk-ros-pkg/jsk_visualization/pull/557.patch
>    - https://github.com/jsk-ros-pkg/jsk_visualization/pull/557.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/pull/557>.
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
because of these line of genjava:
https://github.com/rosjava/genjava/blob/indigo/src/genjava/gradle_project.py#L125-L127

maybe genjava is not installed on travis. so it passes.

**Comment by wkentaro** [comment]
If I'm not missing something:

* geneus checks `msg/srv` directory existence to know that, and generate messages with declaration in find_package.
* genjava checks `msg/srv` directory existence to know that, generate messages all times and raise error when `message_generation` or `genmsg` is not listed as `build_depend` in package.xml because it's not valid configuration.

https://github.com/rosjava/genjava/blob/indigo/src/genjava/gradle_project.py#L151-L152

**Comment by wkentaro** [comment]
I updated the commit, and I think now it looks good by refering to ros tutorial.
https://github.com/ros/ros_tutorials/blob/jade-devel/roscpp_tutorials/CMakeLists.txt
https://github.com/ros/ros_tutorials/blob/jade-devel/roscpp_tutorials%2Fpackage.xml

**Pull request merged**
