### PR TITLE
Fix moc generation errors with boost >= 1.57 (for OS X currently)

### PR DESCRIPTION
**Pull request by wkentaro**
tag: pkg/jsk_rviz_plugins, feature

Please refer to https://github.com/ros-visualization/rviz/pull/826

### CODE REVIEW

**Comment by wkentaro** [comment]
With this PR jsk_rviz_plugins works on OS X.
screen shot 2016-06-01 at 20 47 49

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
test is failing

**Comment by wkentaro** [comment]
> test is failing

?

image

**Comment by k-okada** [comment]
sorry, i missed that, btw why just add `+#ifndef Q_MOC_RUN` works?

**Comment by wkentaro** [comment]
This is a bug in Qt4 MOC compilier: https://bugreports.qt.io/browse/QTBUG-22829
When Qt programs are being built, the moc target is also built.

**Pull request merged**
