### PR TITLE
[jsk_rqt_plugins] Warn about unsupported topic type

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
image

**Comment by k-okada** [comment]
why you have to specify the version of jsk_common? why latest fails?

**Comment by wkentaro** [comment]
Unexpectedly it builds bing.cpp.
``


In file included from /workspace/ros/ws_jsk_visualization/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bing.cpp:36:0:


/workspace/ros/ws_jsk_visualization/src/jsk-ros-pkg/jsk_recognition/jsk_perception/include/jsk_perception/bing.h:43:32: fatal error: opencv2/saliency.hpp: No such file or directory


compilation terminated.


make[2]: *** [CMakeFiles/jsk_perception.dir/src/bing.cpp.o] Error 1


make[1]: *** [CMakeFiles/jsk_perception.dir/all] Error 2


make: *** [all] Error 2


[jsk_perception] <== '/workspace/ros/ws_jsk_visualization/build/jsk_perception/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'

```

**Comment by k-okada** [comment]
so why jsk_recognition passed on the travis?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Because it does not build bing.cpp.

**Comment by wkentaro** [comment]
plz merge

**Pull request merged**
