### PR TITLE
Use gcc -z defs to check undefined symbols in shared objects

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
*jsk_rviz_plugins* has linking error:

```
[jsk_rviz_plugins] CMakeFiles/jsk_rviz_plugins.dir/src/moc_publish_topic.cxx.o: In function `jsk_rviz_plugins::PublishTopic::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':                                                                    
[jsk_rviz_plugins] /home/wkentaro/ros/indigo/build/jsk_rviz_plugins/src/moc_publish_topic.cxx:54: undefined reference to `jsk_rviz_plugins::PublishTopic::sendVel()'                                                                                           
[jsk_rviz_plugins] CMakeFiles/jsk_rviz_plugins.dir/src/moc_cancel_action.cxx.o: In function `jsk_rviz_plugins::CancelAction::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':                                                                    
[jsk_rviz_plugins] /home/wkentaro/ros/indigo/build/jsk_rviz_plugins/src/moc_cancel_action.cxx:58: undefined reference to `jsk_rviz_plugins::CancelAction::setTopic(QString const&)'                                                                            
[jsk_rviz_plugins] /home/wkentaro/ros/indigo/build/jsk_rviz_plugins/src/moc_cancel_action.cxx:59: undefined reference to `jsk_rviz_plugins::CancelAction::updateTopic()'                                                                                       
[jsk_rviz_plugins] CMakeFiles/jsk_rviz_plugins.dir/src/moc_record_action.cxx.o: In function `jsk_rviz_plugins::RecordAction::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':                                                                    
[jsk_rviz_plugins] /home/wkentaro/ros/indigo/build/jsk_rviz_plugins/src/moc_record_action.cxx:58: undefined reference to `jsk_rviz_plugins::RecordAction::setTopic(QString const&)'                                                                            
[jsk_rviz_plugins] /home/wkentaro/ros/indigo/build/jsk_rviz_plugins/src/moc_record_action.cxx:59: undefined reference to `jsk_rviz_plugins::RecordAction::updateTopic()'                                                                                       
[jsk_rviz_plugins] /home/wkentaro/ros/indigo/build/jsk_rviz_plugins/src/moc_record_action.cxx:60: undefined reference to `jsk_rviz_plugins::RecordAction::commandPlay()'                                                                                       
[jsk_rviz_plugins] collect2: error: ld returned 1 exit status                                                                                                                                                                                                  
[jsk_rviz_plugins] make[2]: *** [/home/wkentaro/ros/indigo/devel/lib/libjsk_rviz_plugins.so] Error 1                                                                                                                                                           
[jsk_rviz_plugins] make[1]: *** [CMakeFiles/jsk_rviz_plugins.dir/all] Error 2                                                                                                                                                                                  
[jsk_rviz_plugins] make: *** [all] Error 2                                                                                                                                                                                                                     
[jsk_rviz_plugins] <== '/home/wkentaro/ros/indigo/build/jsk_rviz_plugins/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' failed with return code '2'                                                                                                        
Failed   <== jsk_rviz_plugins       [ 6.4 seconds ]  
```

**Comment by garaemon** [comment]
https://github.com/wkentaro/jsk_visualization/pull/1 should solve this issue

**Comment by garaemon** [comment]
oops, it does not solve the issue.

**Comment by garaemon** [comment]
I found these methods are not defined. 
It is a bug revealed by -z degs

**Pull request merged**
