### PR TITLE
[jsk_rviz_plugins] Add "Align Bottom" option to OverlayText

### PR DESCRIPTION
**Pull request by YutoUchimi**
This PR mainly focuses on improving visualization of ROS console output on Rviz.

__1. Align Bottom option__

Before this PR, `OverlayText` plugin showed text only at the top of the window.

screenshot from 2018-12-14 17-00-58

With this PR, users can select the place of drawn text by toggling `AlignBottom` checkbox.

screenshot from 2018-12-14 16-58-24

__2. ~reverse_lines parameter__

This PR also supports a new parameter in `rosconsole_overlay_text.py`.
In default, the order of output messages shown in rviz is reversed. For example,
```
2018/12/14 17:57:42 baz
2018/12/14 17:57:41 bar
2018/12/14 17:57:40 foo
```

However, if set this paramter to false, you will see
```
2018/12/14 17:57:40 foo
2018/12/14 17:57:41 bar
2018/12/14 17:57:42 baz
```

---

Progress
- [x] Add align bottom option
- [x] Support reversing lines
- [x] Add documentation

### CODE REVIEW

**Comment by k-okada** [comment]
I can not see 'Align Bottom" option' on doc/jsk_rviz_plugins/nodes/images/rosconsole_overlay_text.png

**Comment by YutoUchimi** [comment]
@k-okada Thank you for your comment.
I updated the image just now.

**Comment by k-okada** [comment]
image
seems much better for me, what the reason not to use this image ?

**Comment by YutoUchimi** [comment]
That image is not the result of `roslaunch jsk_rviz_plugins overlay_sample.launch`.
This is why I don't use it, but I won't stick to my rule. So I will update to use the image you suggested.

**Comment by k-okada** [comment]
ok, if so, please increase the number of vertical line of
overlay_sample.launch, so that uses can easy understand the effect of
'Align bottom'

--
◉ Kei Okada

--
◉ Kei Okada



2018年12月17日(月) 17:59 Yuto Uchimi <notifications@github.com>:

**Pull request merged**
