### PR TITLE
Support custom color for OverlayMenu

### PR DESCRIPTION
**Pull request by furushchev**
Added option `fg_color`/`bg_color` for `OverlayMenu`.
(same function as `OverlayText`)

ezgif com-video-to-gif

### CODE REVIEW

**Comment by knorth55** [comment]
it is great feature, but this PR includes message definition change.
the message definition change can be splitted from this PR and merge it later for quick merging.

**Comment by furushchev** [comment]
@knorth55 Thanks for the comment. Created another PR. Once it is merged, I will rebase this PR.

**Comment by furushchev** [comment]
@knorth55 Kindly ping to maintainer

**Comment by k-okada** [comment]
thanks,

do we need message conversion tool? or allow plugin  to take AnyMsg and
interpret them?
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_utils/scripts/marker_msg_from_indigo_to_kinetic.py
https://github.com/jsk-ros-pkg/jsk_robot/pull/898

--
◉ Kei Okada



2020年8月18日(火) 16:53 Yuki Furuta <notifications@github.com>:

**Comment by k-okada** [comment]
> you mean a use case that rviz and a sender of jsk_rviz_plugins/OverlayMenu is
running on different distros?

yes, and in order to do that, we need to receive the same type name for
different definitions. And to do that , we need to use AnyMSg or
ShapeShifter, see
https://github.com/jsk-ros-pkg/jsk_robot/blob/e9157f2db0c2f74454c5e403552366a3ca1ef5c1/jsk_robot_common/jsk_robot_utils/scripts/marker_msg_from_indigo_to_kinetic.py
for
example.
--
◉ Kei Okada



2020年8月22日(土) 15:38 Yuki Furuta <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Sorry for the delay. Added a script to bridge new/old OverlayMenu messages like the one you mentioned above. Please could you check?

**Pull request merged**
