### PR TITLE
Object 3d annotation using transformable interactive marker

### PR DESCRIPTION
**Pull request by wkentaro**
Depends on https://github.com/jsk-ros-pkg/jsk_recognition/pull/2148

## Why?

I'd like to spawn mesh models using rviz panel.

object_3d_annotation_002

### CODE REVIEW

**Comment by wkentaro** [comment]
Today, @YutoUchimi requested me to merge this feature to master, so I will try a bit.

**Comment by wkentaro** [comment]
## Sample

```bash
wstool set start-jsk/jsk_apc https://github.com/jsk-ros-pkg/jsk_recognition.git --git -v 1.2.0 -y
wstool set start-jsk/jsk_apc https://github.com/start-jsk/jsk_apc.git --git -v 4.2.0 -y
# wstool set start-jsk/jsk_apc https://github.com/wkentaro/jsk_visualization.git --git -v 3d_annotation -y
wstool set start-jsk/jsk_apc https://github.com/jsk-ros-pkg/jsk_visualization.git --git -v master -y
wstool up -j3

catkin build jsk_recognition_msgs jsk_arc2017_common jsk_rviz_plugins

roslaunch jsk_recognition_msgs sample_object_array_publisher.launch
rviz
# add panel of TransformableMarkerOperatiorAction
```

**Comment by wkentaro** [comment]
```
Errors << jsk_interactive_marker:make /home/travis/ros/ws_jsk_visualization/logs/jsk_interactive_marker/build.make.000.log
In file included from [01m[K/home/travis/ros/ws_jsk_visualization/build/jsk_interactive_marker/include/jsk_interactive_marker/rviz_plugins/moc_transformable_marker_operator.cpp:9:0[m[K:

[01m[K/home/travis/ros/ws_jsk_visualization/build/jsk_interactive_marker/include/jsk_interactive_marker/rviz_plugins/../../../../../src/jsk_visualization/jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/rviz_plugins/transformable_marker_operator.h:13:46:[m[K [01;31m[Kfatal error: [m[Kjsk_recognition_msgs/ObjectArray.h: No such file or directory

compilation terminated.

make[2]: *** [CMakeFiles/jsk_interactive_marker.dir/include/jsk_interactive_marker/rviz_plugins/moc_transformable_marker_operator.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....
```

@k-okada it seems that `jsk_recognition_msgs` is too old.
screen shot 2017-11-16 at 0 52 53

**Comment by wkentaro** [comment]
It seems that debbuild of `jsk_perception` fails because of the fail of `opencv_apps`: https://github.com/ros-perception/opencv_apps/issues/72.
And I guess that's why you don't release jsk_recognition 1.2.0 to kinetic. So the root problem of this PR seems https://github.com/ros-perception/opencv_apps/issues/72.

**Comment by wkentaro** [comment]
@k-okada Could you please release jsk_recognition 1.2.0 to kinetic.

**Comment by k-okada** [comment]
https://github.com/ros/rosdistro/pull/16454
released on indigo/kinetic, jade is already EOF, so we could not have newer one. May be we can drop from .travis

**Comment by wkentaro** [comment]
@k-okada Pass the tests. Could you please review this?

**Comment by wkentaro** [comment]
@k-okada Is this solution better than adding `version_gt="1.2.0"` to package.xml?

**Comment by k-okada** [comment]
>  adding version_gt="1.2.0" to package.xml?

this just show warning, but continue to compile source code.
I'm afraid, pull latest jsk_visualizaiton, have compile error, try to debug
for few days, some one advice to use latest jsk_recognitoin, checkout
latest jsk_recognitoin, fail to compile source code for some reason....If
you can not believe this, you'd  better to attend enshu starting from
today....

when we apt-get install jsk_visualizatoin deb, then it will pull
jsk_recognioin_msgs=1.2.0, so it is very effective for deb users.


--
◉ Kei Okada


2017-11-26 14:11 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
@k-okada Thank you for the explanation. LGTM 👍

**Pull request merged**
