### PR TITLE
[jsk_rviz_plugin] Add rviz button interface for yes/no service request

### PR DESCRIPTION
**Pull request by wkentaro**
Depends on https://github.com/jsk-ros-pkg/jsk_common_msgs/pull/10
```
Client -> jsk_gui_msgs::YesNo -> ThisPlugin
       <-       yes/no        <-
```

### CODE REVIEW

**Comment by wkentaro** [comment]
rviz_yes_no_button_interface_action

**Comment by wkentaro** [comment]
Currently, waiting for release of jsk_common_msgs.

**Comment by k-okada** [comment]
ok, done as  jsk_common_msgs  3.0.0, now it only available on indigo and
later, so you need to add `if(NOT HYDRO)`

--
◉ Kei Okada

**Comment by wkentaro** [comment]
In that case I'll have below error
image

**Comment by wkentaro** [comment]
You mean hydro user want to compile jsk_visualization from source without compiling jsk_common_msgs from source, don't you?
Is that reasonable?

**Comment by wkentaro** [comment]
Unfortunately, jsk_visualization only depends not-apt-released jsk_common_msgs:

- http://www.ros.org/debbuild/hydro.html?q=jsk_common_msgs
- https://github.com/jsk-ros-pkg/jsk_visualization/commit/e8d04d62b6209db62d1544555f1e1d7e9e609a01#diff-b852ac96903980a9bdca56090ebd2b16R10

**Comment by wkentaro** [comment]
The test passed, could you please give me some comments?

**Comment by wkentaro** [comment]
Should I configure the [plugin_description.xml](https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_rviz_plugins/plugin_description.xml) in CMakeLists.txt to remove YesNoButton plugin on hydro?

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Any comments, please?

**Pull request merged**
