### PR TITLE
Run after clang compile

### PR DESCRIPTION
**Pull request by pbeeson**
I was seeing issues where after compiling the jsk_rviz_plugin source with Clang, the use of most any jsk plugin would cause the Ogre window for Rviz to freeze.  After fixing all the compiler warnings from Clang (lots of functions that end with no return value, and some locks without variable names -- things that aren't standard but g++ will "smooth over"), compiling jsk_rviz_plugins runs properly, whether compiled with g++ or with Clang.

### CODE REVIEW

**Comment by k-okada** [comment]
@pbeeson thanks for contribution! BTW which distro are you using? We could check if this PR is compilable with Travis, but do not know if this acutally works. (see  https://github.com/jsk-ros-pkg/jsk_visualization/pull/710, https://github.com/jsk-ros-pkg/jsk_visualization/pull/739, which cause segfault on last indigo release)
 We need volunteers to check this fix actually works with exsisting platforoms, at least kinetic and meloidc, (may be JSK people staill have indigo machine...)

**Comment by pbeeson** [comment]
This work on kinetic and melodic.

All I did was draw the text twice, but offset and darker.  I’d imagine it
works in indigo too, but I no longer have means of testing indigo.

**Comment by pbeeson** [comment]
Sorry, I got my two PRs mixed up.  In response to Clang, I know this works
on 16.04 and 18.04.

All I did was ensure names for the lock variables and made sure that some
functions that had no return values, did actually return values.  So
nothing that requires C++-11 spec or anything, so I’d imagine this would
work with indigo to.  But there was some deadlock happening with Clang that
g++ compile doesn’t have because it makes different assumptions on the
under defined cases above.

It might be possible to spin up a 14.04 Ubuntu machine on Amazon and
install indigo and test this but I’d have to look into that.

**Comment by pbeeson** [comment]
> We need volunteers to check this fix actually works with exsisting platforoms, at least kinetic and meloidc, (may be JSK people staill have indigo machine...)

Prior to me spending a lot of time compiling this on 14.04 (which I'm 100% confident will work), I would recommend looking at the actual diff of this PR.  You should see that the changes are minimal and are C++ v1 compliant (returns in functions, variables with names, and appropriate parenthesis).  That is, this PR has no new functionality.  It simply fixes poor C++ programming syntax, which is undefined, so different compilers treat it differently.

**Pull request closed without merging**
