### PR TITLE
[jsk_rqt_plugins/HistogramPlot] modify to correctly run on kinetic

### PR DESCRIPTION
**Pull request by knorth55**
`Kinetic` uses `qt5`, and `qt5` has different module structure.
I refactor codes and update to use correct module for kinetic.
You can check with
```
roslaunch jsk_perception sample_bof_object_recognition.launch
# or
roslaunch jsk_rqt_plugins sample_histogram.launch
```
bof_histogram

### CODE REVIEW

**Comment by k-okada** [comment]
@iroy do you men we should revert this? if so please add +1 to https://github.com/jsk-ros-pkg/jsk_visualization/pull/704, and also please try to write the test code so that Travis find this error. I think just to write test script that import this file would be ok.

@knorth55 please rewrite the code with system matlab version for now. and if you can find the code to support both system (apt) version and pip version, then create new pull requests.

**Comment by knorth55** [comment]
@k-okada apt matplotlib have error with qt5 (see #688).
In order to prevent the error, we have to remove matplotlib dependency.

**Comment by knorth55** [comment]
or install matplotlib `2.0.0` with `catkin_virtualenv`.

**Comment by k-okada** [comment]
problem in #689? any way please look at
https://github.com/ros-visualization/rqt_plot/blob/master/src/rqt_plot/data_plot/mat_data_plot.py#L54-L89
--
◉ Kei Okada



2018年9月4日(火) 13:31 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
@k-okada thank you, I found the solution.
I will make a PR for solving the problem.
https://github.com/ros-visualization/rqt_plot/blob/master/src/rqt_plot/data_plot/mat_data_plot.py#L62

**Pull request merged**
